apiVersion: v1
kind: Service
metadata:
  name: charts-service
  namespace: charts
spec:
  selector:
    app: charts-app
  type: LoadBalancer
  ports:
    - name: charts-app-port
      protocol: TCP
      port: 10002
      targetPort: 10002
  loadBalancerIP: 192.168.1.142
